SESSIONS = [
    {
        "id": 1,
        "route_name": "Kampus - Terminal Baru",
        "driver_name": "Andi Pratama",
        "departure_time": "06:30",
        "passenger_name": "Rina Sari",
        "destination": "Terminal Baru",
        "seat_count": 2,
        "status": "scheduled",
    },
    {
        "id": 2,
        "route_name": "Asrama - Pusat Kegiatan",
        "driver_name": "Budi Santoso",
        "departure_time": "07:00",
        "passenger_name": "Rizki Hidayat",
        "destination": "Pusat Kegiatan",
        "seat_count": 1,
        "status": "scheduled",
    },
    {
        "id": 3,
        "route_name": "Kampus - Perpustakaan",
        "driver_name": "Citra Lestari",
        "departure_time": "07:15",
        "passenger_name": "Nadya Putri",
        "destination": "Perpustakaan",
        "seat_count": 3,
        "status": "on_route",
    },
    {
        "id": 4,
        "route_name": "Laboratorium - Gedung Rektorat",
        "driver_name": "Dewi Maharani",
        "departure_time": "08:00",
        "passenger_name": "Farhan Alamsyah",
        "destination": "Gedung Rektorat",
        "seat_count": 4,
        "status": "scheduled",
    },
    {
        "id": 5,
        "route_name": "Kampus - Stadion Utama",
        "driver_name": "Eko Nugroho",
        "departure_time": "08:30",
        "passenger_name": "Sinta Dewi",
        "destination": "Stadion Utama",
        "seat_count": 2,
        "status": "completed",
    },
    {
        "id": 6,
        "route_name": "Asrama - Klinik Kampus",
        "driver_name": "Fajar Rahman",
        "departure_time": "09:00",
        "passenger_name": "Tito Wijaya",
        "destination": "Klinik Kampus",
        "seat_count": 1,
        "status": "scheduled",
    },
    {
        "id": 7,
        "route_name": "Kampus - Gedung Fakultas",
        "driver_name": "Gina Novita",
        "departure_time": "09:45",
        "passenger_name": "Maya Putri",
        "destination": "Gedung Fakultas",
        "seat_count": 3,
        "status": "scheduled",
    },
    {
        "id": 8,
        "route_name": "Masjid - Area Parkir",
        "driver_name": "Hendra Wijaya",
        "departure_time": "10:15",
        "passenger_name": "Alya Rahma",
        "destination": "Area Parkir",
        "seat_count": 2,
        "status": "on_route",
    },
    {
        "id": 9,
        "route_name": "Pusat Bisnis - Kampus",
        "driver_name": "Irfan Kurnia",
        "departure_time": "11:00",
        "passenger_name": "Dimas Prakoso",
        "destination": "Kampus",
        "seat_count": 5,
        "status": "scheduled",
    },
    {
        "id": 10,
        "route_name": "Kampus - Terminal Selatan",
        "driver_name": "Jihan Aulia",
        "departure_time": "11:50",
        "passenger_name": "Lutfi Ramadhan",
        "destination": "Terminal Selatan",
        "seat_count": 2,
        "status": "completed",
    },
    {
        "id": 11,
        "route_name": "Asrama - Gedung Serbaguna",
        "driver_name": "Kiki Amelia",
        "departure_time": "12:20",
        "passenger_name": "Wanda Herlina",
        "destination": "Gedung Serbaguna",
        "seat_count": 4,
        "status": "scheduled",
    },
    {
        "id": 12,
        "route_name": "Kampus - Hotel Mahasiswa",
        "driver_name": "Lala Putri",
        "departure_time": "13:10",
        "passenger_name": "Bagas Surya",
        "destination": "Hotel Mahasiswa",
        "seat_count": 1,
        "status": "scheduled",
    },
]
